# Makefile for SetID pass

# Path to top level of LLVM hierarchy
LEVEL = ../../..
#LEVEL = /home/karzler/llvm/build
# Name of the library to build
LIBRARYNAME = SetID

# Make the shared library become a loadable module so the tools can
# dlopen/dlsym on the resulting library.
LOADABLE_MODULE = 1

# Include the makefile implementation stuff
include $(LEVEL)/Makefile.common
